### PR TITLE
fix: wrong sass file ending

### PR DESCRIPTION
**Pull request by cimchd**
I had problems with the import due to file /form/_all.scss. After a check i saw that there was still the file ending .sass. After deleting it, everything worked fine for me.

### CODE REVIEW

**Comment by j1mc** [comment]
it's funny ... i saw that you had forked my repo, and i went to check out the diff of your fork, saw that you fixed something, then i made those changes and pushed them before you even submitted your pull request.  : ) 

i'll close this request, but this should be fixed.  i thanked you in the git commit message.  : )

**Comment by cimchd** [comment]
Are you planning to update the npm package also?

**Comment by j1mc** [comment]
Thanks for the reminder - I just published the update.  : )

**Comment by cimchd** [comment]
Thanks a lot :-D

**Pull request closed without merging**
